server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location /orgs/ {
    proxy_pass http://api:3001/orgs/;
    proxy_http_version 1.1;
  }

  location /orgs {
    proxy_pass http://api:3001/orgs;
    proxy_http_version 1.1;
  }

  location /query {
    proxy_pass http://api:3001/query;
    proxy_http_version 1.1;
  }

  location /health {
    proxy_pass http://api:3001/health;
  }

  location /events/ {
    proxy_pass http://api:3001/events/;
    proxy_http_version 1.1;
    proxy_set_header Connection '';
    proxy_buffering off;
    proxy_cache off;
    chunked_transfer_encoding off;
    proxy_read_timeout 24h;
  }

  location /events {
    proxy_pass http://api:3001/events;
    proxy_http_version 1.1;
    proxy_set_header Connection '';
    proxy_buffering off;
    proxy_cache off;
    chunked_transfer_encoding off;
    proxy_read_timeout 24h;
  }
}
