server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location /orgs/ {
    proxy_pass http://api:3001/orgs/;
    proxy_http_version 1.1;
  }

  location /orgs {
    proxy_pass http://api:3001/orgs;
    proxy_http_version 1.1;
  }

  location /query {
    proxy_pass http://api:3001/query;
    proxy_http_version 1.1;
  }

  location /health {
    proxy_pass http://api:3001/health;
  }

  location /ws {
    proxy_pass http://api:3001/ws;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }
}
